# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-08 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='estacion',
            name='token',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
