# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-10 00:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0002_estacion_token'),
    ]

    operations = [
        migrations.CreateModel(
            name='Combustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(blank=True, max_length=4, null=True, unique=True)),
                ('nombre', models.CharField(max_length=60)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Combustibles',
            },
        ),
        migrations.CreateModel(
            name='PrecioCombustible',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=3, max_digits=4)),
                ('combustible', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmaestros.Combustible')),
            ],
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='petroleo_95',
        ),
        migrations.RemoveField(
            model_name='estacion',
            name='petroleo_diesel',
        ),
        migrations.AddField(
            model_name='preciocombustible',
            name='estacion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmaestros.Estacion'),
        ),
        migrations.AddIndex(
            model_name='combustible',
            index=models.Index(fields=['codigo'], name='fmaestros_c_codigo_4fdec4_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='preciocombustible',
            unique_together=set([('estacion', 'combustible')]),
        ),
    ]
