# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-10 20:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0003_auto_20210310_0004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combustible',
            name='codigo',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='estacion',
            name='codigo',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='provincia',
            name='codigo',
            field=models.CharField(max_length=16, unique=True),
        ),
    ]
