# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-18 21:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0004_auto_20210310_2019'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComunidadAutonoma',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=2, unique=True)),
                ('codigo_iso', models.CharField(max_length=4, unique=True)),
                ('nombre', models.CharField(max_length=32)),
            ],
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='fecha_creacion',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='fecha_modificacion',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='fecha_paso_historico',
        ),
        migrations.RemoveField(
            model_name='provincia',
            name='observaciones',
        ),
        migrations.AddField(
            model_name='provincia',
            name='ccaa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fmaestros.ComunidadAutonoma'),
            preserve_default=False,
        ),
    ]
