# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-07 02:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fmaestros', '0005_auto_20210318_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciocombustible',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
