# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-10 01:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repostajes', '0003_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repostaje',
            name='combustible',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fmaestros.Combustible'),
        ),
    ]
