# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-04-07 17:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repostajes', '0004_auto_20210310_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='repostaje',
            name='precio',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
    ]
