# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-02 20:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_matricula'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='matricula',
            options={'verbose_name_plural': 'Matriculas'},
        ),
        migrations.AddIndex(
            model_name='matricula',
            index=models.Index(fields=[b'codigo'], name='usuarios_ma_codigo_d5030d_idx'),
        ),
    ]
