# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-04 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20210304_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='telefono',
        ),
    ]
