# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2021-03-05 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20210304_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='nif',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
